[package]
name = "archangel-exec-format"
description = "Parser and signature verifier for the .exec bundle format."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
archangel-core = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
ed25519-dalek = { workspace = true }
sha2 = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
