//! `archangelctl setup` — the one-command bootstrap wizard.
//!
//! Orchestrates the steps that were manual in early v0.1 (key, trust,
//! sample bundle signing, allowlist, config) into one **idempotent,
//! fail-closed** command. Security rules it never breaks:
//!
//! - It **never overwrites** an operator-owned security artifact: the
//!   operator key, the allowlist, or the main config. If one exists it is
//!   kept and reported, never silently rewritten (silently changing
//!   policy or identity would be exactly the wrong behavior).
//! - It only ever *adds* (creates-if-absent), with least-privilege modes.
//! - The generated config is validated with the real fail-closed schema
//!   before setup is declared successful.
//! - The LLM token is never handled here (no echo, no argv) — that is
//!   done by the caller with a no-echo prompt / file, written `0600`.

use std::path::{Path, PathBuf};

use archangel_config::Config;
use archangel_exec_format::{OperatorTrust, VerifiedBundle};

use crate::{
    doctor,
    error::CtlError,
    keys,
    render::Palette,
};

/// Inputs for [`run`].
#[derive(Debug, Clone)]
pub struct SetupOptions {
    /// Config root (e.g. `/etc/archangel`).
    pub etc: PathBuf,
    /// `anthropic` or `ollama`.
    pub backend: String,
    /// UID of the human operator (control socket peer gate).
    pub operator_uid: u32,
    /// UID `archangeld` runs as (exec socket peer gate).
    pub daemon_uid: u32,
    /// Optional non-default Ollama URL to record for reference.
    pub ollama_url: Option<String>,
}

/// The real operator UID, honoring `sudo`.
///
/// Prefers `SUDO_UID`, else the real uid from `/proc/self/status`. Returns
/// `None` if it cannot be determined (the caller must then require an
/// explicit `--operator-uid`).
#[must_use]
pub fn detect_operator_uid() -> Option<u32> {
    if let Ok(s) = std::env::var("SUDO_UID") {
        if let Ok(n) = s.trim().parse() {
            return Some(n);
        }
    }
    let status = std::fs::read_to_string("/proc/self/status").ok()?;
    uid_from_proc_status(&status)
}

/// Parse the real UID (first field of the `Uid:` line) — pure, testable.
#[must_use]
pub fn uid_from_proc_status(status: &str) -> Option<u32> {
    for line in status.lines() {
        if let Some(rest) = line.strip_prefix("Uid:") {
            return rest.split_whitespace().next()?.parse().ok();
        }
    }
    None
}

/// Look up a system user's UID in `/etc/passwd` contents — pure, testable.
#[must_use]
pub fn uid_from_passwd(passwd: &str, user: &str) -> Option<u32> {
    for line in passwd.lines() {
        let mut f = line.split(':');
        if f.next() == Some(user) {
            // user:x:UID:GID:...
            return f.nth(1)?.parse().ok();
        }
    }
    None
}

/// `archangel` system user's UID, or `None` if there is no such account.
#[must_use]
pub fn detect_daemon_uid() -> Option<u32> {
    let passwd = std::fs::read_to_string("/etc/passwd").ok()?;
    uid_from_passwd(&passwd, "archangel")
}

/// Render a valid, conservative `archangel.toml`. The result is validated
/// by the real schema before it is ever written.
#[must_use]
pub fn render_config(opts: &SetupOptions) -> String {
    let e = opts.etc.display();
    let model_line = if opts.backend == "anthropic" {
        "model = \"claude-opus-4-7\"\n"
    } else {
        "# model = \"...\"   # omit to use the per-backend default\n"
    };
    format!(
        "# Generated by `archangelctl setup`. Review before production use.\n\
         [daemon]\n\
         trust_store     = \"{e}/trust/operators.pubkeys\"\n\
         audit_log       = \"/var/log/archangel/audit.log.jsonl\"\n\
         audit_key       = \"{e}/trust/audit.key\"\n\
         operator_pubkey = \"{e}/trust/operator.pub\"\n\
         allowlist       = \"{e}/policies/allowlist.toml\"\n\
         bundle_dir      = \"{e}/exec\"\n\
         session_pub     = \"/run/archangel/session.pub\"\n\
         \n\
         [sockets]\n\
         control      = \"/run/archangel/ctl.sock\"\n\
         control_mode = 0o660\n\
         exec         = \"/run/archangel/exec.sock\"\n\
         operator_uid = {ouid}\n\
         daemon_uid   = {duid}\n\
         \n\
         [modes]\n\
         # v0.1 is the read-only milestone; the executor enforces this.\n\
         default = \"read_only\"\n\
         autonomous_allowed = false\n\
         \n\
         [llm]\n\
         default_backend = \"{backend}\"\n\
         {model_line}max_tokens = 1024\n",
        ouid = opts.operator_uid,
        duid = opts.daemon_uid,
        backend = opts.backend,
    )
}

/// Default allowlist permitting exactly the verified read-only bundles.
#[must_use]
pub fn render_allowlist(read_only_execs: &[String]) -> String {
    let list = read_only_execs
        .iter()
        .map(|n| format!("\"{n}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "# Generated by `archangelctl setup` from the verified read-only\n\
         # bundles in the exec dir. Review and tighten as needed.\n\
         [[profile]]\n\
         name = \"default\"\n\
         mode = \"read_only\"\n\
         allowed_exec = [{list}]\n"
    )
}

/// Decide the new `operators.pubkeys` content. Returns `None` if the
/// operator key is already present (idempotent; never drops other keys).
#[must_use]
pub fn operators_pubkeys_update(
    existing: Option<&str>,
    operator_pub_hex: &str,
) -> Option<String> {
    let key = operator_pub_hex.trim();
    existing.map_or_else(
        || Some(format!("{key}  operator\n")),
        |content| {
            let present = content
                .lines()
                .any(|l| l.split_whitespace().next() == Some(key));
            if present {
                None
            } else {
                Some(format!(
                    "{}\n{key}  operator (added by setup)\n",
                    content.trim_end()
                ))
            }
        },
    )
}

fn write_new(path: &Path, content: &str, mode: u32) -> Result<(), CtlError> {
    use std::{io::Write as _, os::unix::fs::OpenOptionsExt as _};
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(mode)
        .open(path)
        .map_err(|e| CtlError::Key(format!("create {}: {e}", path.display())))?;
    f.write_all(content.as_bytes())
        .map_err(|e| CtlError::Key(format!("write {}: {e}", path.display())))
}

/// Verified read-only bundle names in `exec_dir` under `trust`.
fn verified_read_only(exec_dir: &Path, trust: &OperatorTrust) -> Vec<String> {
    let mut names = Vec::new();
    let Ok(rd) = std::fs::read_dir(exec_dir) else {
        return names;
    };
    for entry in rd.flatten() {
        let p = entry.path();
        if p.extension().and_then(|x| x.to_str()) != Some("exec") {
            continue;
        }
        let Some(stem) = p.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let sig = exec_dir.join(format!("{stem}.exec.sig"));
        if let Ok(b) = VerifiedBundle::load(&p, &sig, trust) {
            if b.manifest().meta.read_only {
                names.push(b.manifest().meta.name.clone());
            }
        }
    }
    names.sort();
    names
}

/// Run the wizard. Idempotent and fail-closed; returns a human report.
pub fn run(opts: &SetupOptions, palette: Palette) -> Result<String, CtlError> {
    let mut log: Vec<String> = Vec::new();
    let trust_dir = opts.etc.join("trust");
    let pol_dir = opts.etc.join("policies");
    let exec_dir = opts.etc.join("exec");
    for d in [&opts.etc, &trust_dir, &pol_dir, &exec_dir] {
        std::fs::create_dir_all(d)
            .map_err(|e| CtlError::Key(format!("mkdir {}: {e}", d.display())))?;
    }

    // 1. Operator key (never clobbered: init refuses if it exists).
    let sk = trust_dir.join("operator.key");
    let pk = trust_dir.join("operator.pub");
    if sk.exists() {
        log.push(format!("operator key: kept existing {}", sk.display()));
    } else {
        let pub_hex = keys::init_operator_key(&sk, &pk)?;
        log.push(format!("operator key: created ({pub_hex})"));
    }
    let operator_pub_hex = std::fs::read_to_string(&pk)
        .map_err(|e| CtlError::Key(format!("read operator.pub: {e}")))?;

    // 2. operators.pubkeys (add operator key; never drop others).
    let operators_path = trust_dir.join("operators.pubkeys");
    let existing = std::fs::read_to_string(&operators_path).ok();
    match operators_pubkeys_update(existing.as_deref(), &operator_pub_hex) {
        None => log.push("operators.pubkeys: operator key already trusted".into()),
        Some(content) => {
            if operators_path.exists() {
                std::fs::write(&operators_path, content).map_err(|e| {
                    CtlError::Key(format!("update operators.pubkeys: {e}"))
                })?;
                log.push("operators.pubkeys: added operator key".into());
            } else {
                write_new(&operators_path, &content, 0o640)?;
                log.push("operators.pubkeys: created".into());
            }
        }
    }

    // 3. Sign any unsigned bundles in the exec dir.
    if let Ok(rd) = std::fs::read_dir(&exec_dir) {
        for entry in rd.flatten() {
            let p = entry.path();
            if p.extension().and_then(|x| x.to_str()) != Some("exec") {
                continue;
            }
            let mut sigp = p.clone().into_os_string();
            sigp.push(".sig");
            if Path::new(&sigp).exists() {
                continue;
            }
            keys::sign_bundle(&sk, &p)?;
            log.push(format!(
                "signed bundle {}",
                p.file_name().and_then(|n| n.to_str()).unwrap_or("?")
            ));
        }
    }

    // 4. Allowlist (never overwrite an operator-authored one).
    let allowlist = pol_dir.join("allowlist.toml");
    if allowlist.exists() {
        log.push("allowlist: kept existing (not overwritten)".into());
    } else {
        let trust = OperatorTrust::load(&operators_path)
            .map_err(|e| CtlError::Key(format!("load trust: {e}")))?;
        let names = verified_read_only(&exec_dir, &trust);
        write_new(&allowlist, &render_allowlist(&names), 0o640)?;
        log.push(format!("allowlist: created (read-only execs: {names:?})"));
    }

    // 5. Main config (never overwrite an operator-edited one). Validate
    //    our template with the real schema before writing.
    let cfg_path = opts.etc.join("archangel.toml");
    if cfg_path.exists() {
        log.push("archangel.toml: kept existing (not overwritten)".into());
    } else {
        let rendered = render_config(opts);
        Config::from_toml(&rendered).map_err(|e| {
            CtlError::Key(format!("generated config failed validation: {e}"))
        })?;
        write_new(&cfg_path, &rendered, 0o640)?;
        log.push("archangel.toml: created and validated".into());
    }

    // 6. Validate whatever config is now in place (fail-closed).
    Config::load(&cfg_path)
        .map_err(|e| CtlError::Key(format!("config does not validate: {e}")))?;

    // 7. Preflight.
    let report = doctor::diagnose(&opts.etc, &sk);
    let mut out = String::new();
    out.push_str("Setup steps:\n");
    for l in &log {
        out.push_str("  - ");
        out.push_str(l);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&report.render(palette));
    Ok(out)
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use std::sync::atomic::{AtomicU32, Ordering};

    use crate::render::Palette;

    use super::{
        operators_pubkeys_update, render_allowlist, render_config, run,
        uid_from_passwd, uid_from_proc_status, SetupOptions,
    };

    fn tmp() -> std::path::PathBuf {
        static N: AtomicU32 = AtomicU32::new(0);
        let d = std::env::temp_dir().join(format!(
            "archangelctl-setup-{}-{}",
            std::process::id(),
            N.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&d).expect("mkdir");
        d
    }

    fn opts(etc: std::path::PathBuf) -> SetupOptions {
        SetupOptions {
            etc,
            backend: "ollama".to_owned(),
            operator_uid: 1000,
            daemon_uid: 1000,
            ollama_url: None,
        }
    }

    #[test]
    fn parses_uids() {
        assert_eq!(
            uid_from_proc_status("Name:\tx\nUid:\t1000\t1000\t1000\t1000\n"),
            Some(1000)
        );
        assert_eq!(
            uid_from_passwd("root:x:0:0::/root:/bin/sh\narchangel:x:996:996::/n:/usr/sbin/nologin\n", "archangel"),
            Some(996)
        );
        assert_eq!(uid_from_passwd("root:x:0:0::/:/sh\n", "archangel"), None);
    }

    #[test]
    fn rendered_config_validates_against_real_schema() {
        let c = render_config(&opts("/etc/archangel".into()));
        // The wizard's own template must satisfy the fail-closed schema.
        assert!(archangel_config::Config::from_toml(&c).is_ok(), "{c}");
        assert!(c.contains("default = \"read_only\""));
        assert!(c.contains("operator_uid = 1000"));
    }

    #[test]
    fn anthropic_template_pins_opus() {
        let mut o = opts("/etc/archangel".into());
        o.backend = "anthropic".to_owned();
        let c = render_config(&o);
        assert!(c.contains("claude-opus-4-7"));
        assert!(archangel_config::Config::from_toml(&c).is_ok());
    }

    #[test]
    fn operators_pubkeys_is_idempotent_and_additive() {
        let k = "aa".repeat(32);
        // Fresh.
        assert_eq!(
            operators_pubkeys_update(None, &k),
            Some(format!("{k}  operator\n"))
        );
        // Already present → no change.
        assert_eq!(
            operators_pubkeys_update(Some(&format!("{k}  someone\n")), &k),
            None
        );
        // Different key present → appended, old kept.
        let other = "bb".repeat(32);
        let updated =
            operators_pubkeys_update(Some(&format!("{other}  bob\n")), &k).expect("add");
        assert!(updated.contains(&other), "must not drop existing keys");
        assert!(updated.contains(&k));
    }

    #[test]
    fn allowlist_render_is_read_only_profile() {
        let a = render_allowlist(&["read-uptime".to_owned()]);
        assert!(a.contains("mode = \"read_only\""));
        assert!(a.contains("name = \"default\""));
        assert!(a.contains("allowed_exec = [\"read-uptime\"]"));
    }

    #[test]
    fn run_is_idempotent_and_never_clobbers() {
        let d = tmp();
        let o = opts(d.clone());
        let r1 = run(&o, Palette::fixed(false)).expect("first run");
        assert!(r1.contains("operator key: created"));
        assert!(r1.contains("archangel.toml: created"));
        // Capture the operator key bytes; a second run must not change it.
        let key1 =
            std::fs::read(d.join("trust/operator.key")).expect("key exists");
        let r2 = run(&o, Palette::fixed(false)).expect("second run");
        assert!(r2.contains("kept existing"));
        let key2 = std::fs::read(d.join("trust/operator.key")).expect("key");
        assert_eq!(key1, key2, "operator key must never be rewritten");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn run_produces_a_validatable_config() {
        let d = tmp();
        run(&opts(d.clone()), Palette::fixed(false)).expect("setup");
        let cfg = archangel_config::Config::load(&d.join("archangel.toml"));
        assert!(cfg.is_ok(), "{cfg:?}");
        let _ = std::fs::remove_dir_all(&d);
    }
}
